In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Aufgabe 2: Singulärwerte berechnen
<img src="assets/Bildschirmfoto 2022-05-10 um 14.43.03.png"/>

__Note:__
Jede $(I \times J)$ Matrix $A$ mit Rang $K$ kann gemäß der Singulärwertzerlegug wie folgt zerlegt werden: $$A = UDV' $$
wobei
- $D$ eine Diagonalmatrix ist mit Einträgen $\alpha_1 ≥ \alpha_2 ≥ ... ≥ \alpha_K > 0$ ist
- Die Matrizen $U$ und $V$ bestehen aus orthonormalen Vektoren $u_k$ und $v_k$ mit $k = 1, ..., K$. Ihre Spalten bilden jeweils eine (normierte) Basis eines $K$-dimensionalen Unterraums des $\mathbb{R}^I$ bzw. $\mathbb{R}^J$.
- Es gilt $U'U = V'V = I_K$

Definiert man $$F = UD \text{ und } G = DV'$$ so erhält man die Koordinaten der Zeilen (bzw. Spalten) von $A$ bezüglich der Basisvektoren in $V$ (bzw. $U$). Der Ausdruck ganz oben, lässt sich auch schreiben als: $$A=\sum_{k=1}^K \alpha_k u_k v_k' $$

In [2]:
# Gegebene Matrix:
A = np.array([
    [1, 2],
    [2, 1]
])

# Compute Single Value Decomposition:
## u = unitary/orthogonale matrix
## s = Vector with the singular values
## v = unitary/orthogonale matrix (already Transposed!)
U, S, V = np.linalg.svd(a = A)
# Invert sign (so its still correct)
U = (-1) * U
V = (-1) * V
# Put s as diagonal matrix
D = np.diag(S)
print(f"Orthogonale matrix U = \n{U}")
print(f"Diagonalmatrix der Singularwerte D = \n{D}")
print(f"Orthogonale Matrix V' = \n{V}")

print("Berechnung A = UDV")
print(U @ D @ V)

Orthogonale matrix U = 
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
Diagonalmatrix der Singularwerte D = 
[[3. 0.]
 [0. 1.]]
Orthogonale Matrix V' = 
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
Berechnung A = UDV
[[1. 2.]
 [2. 1.]]


U und V sind orthogonale Matrizen bestehend aus orthonormalen Vektoren $u_k$ bzw. $v_k$ mit $k=1, ..., K$.

In [3]:
# Eigenwerte und Eigenvektor von B = AA'
B = A @ A.T
print(f"AA' =\n {B}")
print(80 * "_")
print("Eigenvalues and Eigenvectors of AA' = B:")
eigenvalue, eigenvector = np.linalg.eig(B)
for i in range(2):
    print(f"{i}th-Eigenvalue = {eigenvalue[i]}")
    print(f"{i}th-Eigenvectors = {eigenvector[:, i]}")

AA' =
 [[5 4]
 [4 5]]
________________________________________________________________________________
Eigenvalues and Eigenvectors of AA' = B:
0th-Eigenvalue = 9.0
0th-Eigenvectors = [0.70710678 0.70710678]
1th-Eigenvalue = 1.0
1th-Eigenvectors = [-0.70710678  0.70710678]


## Approximiere A
__Theorem 5.1.__ Wähle ein $K^* < K$. Dann minimiert die Matrix:
$$ A_{[K^*]} := \sum_{k=1}^{K^*} \alpha_k u_k v_k' $$
den Ausdruck
$$ ||A - X||^2 = \sum_i \sum_j (a_{ij}-x_{ij})^2 $$
unter allen $(I \times J)$-Matrizen $X$ mit einem Rang von maximalen $K^*$.

$A_{[K^*]}$ ist also die bestmöglichste Approximation von $A$ mit $Rang(K^*)$.

In [4]:
# Wähle K* = 1
K_STAR = 2
A_K = 0

for i in range(K_STAR):
    A_K += S[i] * np.tensordot(a=U[:, i], b=V[:, i], axes=0)

A_K

array([[ 2., -1.],
       [ 1., -2.]])

# (Singularvalue decomposition (SVD) example from Standford University, see [youtube](https://www.youtube.com/watch?v=P5mlg91as1c).)

In [5]:
B = np.array([
    [1, 1, 1, 0, 0],
    [3, 3, 3, 0, 0],
    [4, 4, 4, 0, 0],
    [5, 5, 5, 0, 0],
    [0, 2, 0, 4, 4],
    [0, 0, 0, 5, 5],
    [0, 1, 0, 2, 2]
])

# Do SVD and round to 4 decimal places
u, s, v = np.linalg.svd(B)
u = np.around(u, 4)
s = np.around(s, 4)
v = np.around(v, 4)

# B is User - Movie Rating Matrix. Row: User, Column: Movie, Entry: Rating
# Each column in Matrix U represent a "concept". Every entry in column u how much a given user corresponds to a specific "concept". U is "user-to-concept" similarity matrix.
# Singular values in s represent the "strenghts" of every "concept"
# Matrix V is a "movie-to-concept" similarity matrix

# SVD is used to learn "concepts" in our data. In the example from Stanford we identified the "Sci-Fi Concepts" and "Romance Concept", i.e. two movie categories. We can use that for recommendation.

# Aufgabe 2: Berechne die Totale Intertia einer gegebenen Häufigkeitstabelle
<img height="100" src="assets/Bildschirmfoto 2022-05-10 um 15.26.53.png" width="300"/>

__Standardised Matrix Z:__
$$ z_{ij} = \frac{p_{ij}-\hat{e}_{ij}}{\sqrt{\hat{e}_{ij}}} $$

with $p_{ij} = \frac{n_{ij}}{n}$ and $ \hat{e}_{ij} = p_{i\cdot} \cdot p_{\cdot j} $

In [6]:
# Given Data
N = 20
X = np.array([
    [1, 4, 5],
    [4, 4, 2]
])

# Transform X with absolut probability to relative probability, i.e. element wise division with N=20
X = X / N

# Compute relative feature occurence (relative Merkmalshäufigkeit)
p_1x = np.sum(X[0, :])
p_2x = np.sum(X[1, :])
p_x1 = np.sum(X[:, 0])
p_x2 = np.sum(X[:, 1])
p_x3 = np.sum(X[:, 2])

# Compute expected relative value matrix E
E = np.array([
    [p_1x * p_x1, p_1x * p_x2, p_x1 * p_x3],
    [p_2x * p_x1, p_2x * p_x2, p_2x * p_x3]
])

# Standardize X
Z = (X - E)/np.sqrt(E)

# Preview
Z

array([[-0.21213203,  0.        ,  0.54935027],
       [ 0.21213203,  0.        , -0.17928429]])

## Compute Total Inertia

In [7]:
# Compute Total Intertia T from standardised Matrix X, i.e. Z
T = np.sum(Z) ** 2
print(f"Total Inertia T = {T:4f}")

Total Inertia T = 0.136949
